"""Action-horizon lineage accounting independent of a VLA architecture."""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass
from typing import Iterable

from .schedules import ExecutionLevel, HierarchicalSchedule


@dataclass(frozen=True)
class ActionTokenProvenance:
    """Lineage of one position in a cached action chunk."""

    slot: int
    generator_query: int | None
    generator_token: int | None
    correction_depth: int
    synthesized_at_query: int | None
    source: str

    @property
    def generator_backed(self) -> bool:
        return self.generator_query is not None

    def to_dict(self) -> dict[str, int | str | bool | None]:
        return {**asdict(self), "generator_backed": self.generator_backed}


@dataclass(frozen=True)
class ProvenanceSchedule:
    """Schedule derived from horizon exhaustion rather than a copied K value."""

    action_horizon: int
    execution_horizon: int
    full_refresh_interval: int
    first_exhaustion_query: int
    regeneration_interval: int | None
    regeneration_required_before_full_refresh: bool
    levels_through_next_full_refresh: tuple[int, ...]

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def _validate_horizons(action_horizon: int, execution_horizon: int) -> tuple[int, int]:
    horizon = int(action_horizon)
    execution = int(execution_horizon)
    if horizon < 1:
        raise ValueError("action_horizon must be positive")
    if execution < 1 or execution > horizon:
        raise ValueError("execution_horizon must be in [1, action_horizon]")
    return horizon, execution


def original_tokens_remaining(
    action_horizon: int,
    execution_horizon: int,
    correction_queries: int,
) -> int:
    """Return ``max(H - mR, 0)`` after ``m`` correction-only queries."""

    horizon, execution = _validate_horizons(action_horizon, execution_horizon)
    corrections = int(correction_queries)
    if corrections < 0:
        raise ValueError("correction_queries must be nonnegative")
    return max(horizon - corrections * execution, 0)


def first_lineage_exhaustion_query(action_horizon: int, execution_horizon: int) -> int:
    """Return the first correction-query age with no generator-backed token left."""

    horizon, execution = _validate_horizons(action_horizon, execution_horizon)
    return math.ceil(horizon / execution)


def generated_chunk_provenance(
    action_horizon: int,
    *,
    query_index: int,
    source: str,
) -> tuple[ActionTokenProvenance, ...]:
    """Mark every token as freshly generated by an action-transformer decode."""

    horizon = int(action_horizon)
    if horizon < 1 or query_index < 0:
        raise ValueError("action_horizon must be positive and query_index nonnegative")
    return tuple(
        ActionTokenProvenance(
            slot=slot,
            generator_query=int(query_index),
            generator_token=slot,
            correction_depth=0,
            synthesized_at_query=None,
            source=str(source),
        )
        for slot in range(horizon)
    )


def corrected_chunk_provenance(
    previous: Iterable[ActionTokenProvenance],
    *,
    execution_horizon: int,
    query_index: int,
) -> tuple[ActionTokenProvenance, ...]:
    """Apply the exact left-shift plus learned synthetic-tail lineage rule."""

    prior = tuple(previous)
    horizon, execution = _validate_horizons(len(prior), execution_horizon)
    if query_index < 0:
        raise ValueError("query_index must be nonnegative")
    output: list[ActionTokenProvenance] = []
    for slot in range(horizon):
        prior_slot = slot + execution
        if prior_slot < horizon:
            ancestor = prior[prior_slot]
            output.append(
                ActionTokenProvenance(
                    slot=slot,
                    generator_query=ancestor.generator_query,
                    generator_token=ancestor.generator_token,
                    correction_depth=ancestor.correction_depth + 1,
                    synthesized_at_query=ancestor.synthesized_at_query,
                    source="shifted_then_corrected",
                )
            )
        else:
            output.append(
                ActionTokenProvenance(
                    slot=slot,
                    generator_query=None,
                    generator_token=None,
                    correction_depth=1,
                    synthesized_at_query=int(query_index),
                    source="learned_synthetic_tail",
                )
            )
    return tuple(output)


def generator_backed_count(tokens: Iterable[ActionTokenProvenance]) -> int:
    return sum(token.generator_backed for token in tokens)


def derive_provenance_schedule(
    *,
    action_horizon: int,
    execution_horizon: int,
    full_refresh_interval: int,
) -> ProvenanceSchedule:
    """Derive the first complete-chunk regeneration query for one full cycle."""

    horizon, execution = _validate_horizons(action_horizon, execution_horizon)
    full_interval = int(full_refresh_interval)
    if full_interval < 1:
        raise ValueError("full_refresh_interval must be positive")
    exhaustion = first_lineage_exhaustion_query(horizon, execution)
    regeneration_required = exhaustion < full_interval
    regeneration_interval: int | None = exhaustion if regeneration_required else None
    if regeneration_required:
        if full_interval % exhaustion:
            raise ValueError(
                "provenance-derived regeneration interval must divide the fixed full interval"
            )
        schedule = HierarchicalSchedule(full_interval, exhaustion, execution)
        levels = tuple(int(level) for level in schedule.levels(full_interval + 1))
    else:
        levels = tuple(
            int(ExecutionLevel.FULL_REFRESH if index % full_interval == 0 else ExecutionLevel.ACTION_CORRECTION)
            for index in range(full_interval + 1)
        )
    return ProvenanceSchedule(
        action_horizon=horizon,
        execution_horizon=execution,
        full_refresh_interval=full_interval,
        first_exhaustion_query=exhaustion,
        regeneration_interval=regeneration_interval,
        regeneration_required_before_full_refresh=regeneration_required,
        levels_through_next_full_refresh=levels,
    )


def simulate_token_provenance(
    *,
    action_horizon: int,
    execution_horizon: int,
    levels: Iterable[ExecutionLevel | int],
) -> list[dict[str, object]]:
    """Return query- and executed-prefix lineage for a concrete level sequence."""

    horizon, execution = _validate_horizons(action_horizon, execution_horizon)
    chunk: tuple[ActionTokenProvenance, ...] | None = None
    rows: list[dict[str, object]] = []
    for query_index, raw_level in enumerate(levels):
        level = ExecutionLevel(int(raw_level))
        before_count = generator_backed_count(chunk or ())
        if level is ExecutionLevel.ACTION_CORRECTION:
            if chunk is None:
                raise ValueError("action correction cannot precede a generator decode")
            chunk = corrected_chunk_provenance(
                chunk,
                execution_horizon=execution,
                query_index=query_index,
            )
        else:
            chunk = generated_chunk_provenance(
                horizon,
                query_index=query_index,
                source=level.source,
            )
        executed = chunk[:execution]
        rows.append(
            {
                "query_index": query_index,
                "level": int(level),
                "level_source": level.source,
                "generator_backed_before_query": before_count,
                "generator_backed_after_query": generator_backed_count(chunk),
                "executed_generator_backed": generator_backed_count(executed),
                "executed_tokens": [token.to_dict() for token in executed],
                "chunk_tokens": [token.to_dict() for token in chunk],
                "level1_provenance_reset": (
                    generator_backed_count(chunk) == horizon
                    if level is ExecutionLevel.CONDITION_REGENERATION
                    else None
                ),
            }
        )
    return rows


def r1_hybrid_readiness_verdict(
    *,
    implementation_valid: bool,
    lineage_exhausted_before_regeneration: bool,
    measured_regeneration_need: bool,
    pure_action_dominates: bool,
    regeneration_adds_action_transformer_compute: bool,
) -> str:
    """Apply the fixed Protocol-A provenance-readiness decision hierarchy."""

    if not implementation_valid:
        return "R1_HYBRID_IMPLEMENTATION_INVALID"
    if lineage_exhausted_before_regeneration:
        return "R1_HYBRID_PROVENANCE_JUSTIFIED"
    if measured_regeneration_need:
        return "R1_HYBRID_DIAGNOSTIC_ONLY"
    if pure_action_dominates and regeneration_adds_action_transformer_compute:
        return "R1_HYBRID_NOT_JUSTIFIED"
    return "R1_HYBRID_DIAGNOSTIC_ONLY"
