"""Validation-selected V0/V1 adapter training; the frozen pi0.5 model is never optimized."""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import asdict, dataclass
import hashlib
import json
from pathlib import Path
import time
from typing import Any, Literal, Protocol

import torch
from torch import Tensor
from torch.utils.data import DataLoader

from .cache_dataset import LatentLoopSequenceDataset
from .losses import LossWeights, action_losses, composition_loss, normalized_kv_loss, weighted_v0_loss
from .prefix_kv_hook import PrefixKVHook, stack_prefix_kv_states
from .serialization import adapter_checkpoint_config, prefix_embedding_from_record, prefix_state_from_record
from .v0_recursive_unroll import V0AgeInput, recursive_v0_unroll


@dataclass(frozen=True)
class TrainerConfig:
    variant: Literal["v0", "v1", "latent_bridge"]
    max_steps: int
    batch_size: int = 1
    learning_rate: float = 1e-4
    weight_decay: float = 0.0
    max_grad_norm: float = 1.0
    validation_interval: int = 1000
    save_interval: int = 5000
    seed: int = 42
    num_workers: int = 0
    log_interval: int = 20
    wandb_log_interval: int = 100
    execution_horizon: int = 5
    action_horizon: int = 10
    validation_examples: int | None = None
    action_execution_mode: Literal["A", "B"] = "A"


class LatentLoopExampleSource(Protocol):
    """Runtime source for cacheless examples generated by a frozen teacher."""

    provenance: dict[str, Any]

    def iter_train_examples(self) -> Iterator[dict[str, Any]]: ...

    def iter_validation_examples(self, limit: int) -> Iterator[dict[str, Any]]: ...

    def statistics(self) -> dict[str, Any]: ...


def freeze_base_model(model: Any) -> None:
    model.eval()
    for parameter in model.parameters():
        parameter.requires_grad_(False)
    if any(parameter.requires_grad for parameter in model.parameters()):
        raise AssertionError("the base pi0.5 model was not fully frozen")


def optimizer_parameter_names(adapter: torch.nn.Module) -> list[str]:
    names = [name for name, parameter in adapter.named_parameters() if parameter.requires_grad]
    if not names:
        raise ValueError("adapter exposes no trainable parameters")
    return names


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sample_v0_actions_by_age(
    *,
    hook: Any,
    outputs: list[Any],
    steps: list[V0AgeInput],
    mode: Literal["A", "B"],
) -> tuple[list[Tensor], dict[str, float], int]:
    """Evaluate the same all-age action objective sequentially or as one batch."""

    if len(outputs) != len(steps) or not outputs:
        raise ValueError("V0 outputs and age inputs must be nonempty and aligned")
    if mode == "B":
        batch_sizes = [output.transition.state.embeddings.shape[0] for output in outputs]
        predicted_batch, timing = hook.sample_actions_from_state(
            stack_prefix_kv_states([output.transition.state for output in outputs]),
            torch.cat([step.robot_state for step in steps], dim=0),
            torch.cat([output.action_noise for output in outputs], dim=0),
            num_steps=10,
        )
        return list(predicted_batch.split(batch_sizes, dim=0)), timing, 1
    if mode != "A":
        raise ValueError("action execution mode must be A or B")
    predicted_by_age = []
    total_timing = {"cache_rebuild_ms": 0.0, "action_expert_ms": 0.0}
    for output, step in zip(outputs, steps, strict=True):
        predicted, timing = hook.sample_actions_from_state(
            output.transition.state,
            step.robot_state,
            output.action_noise,
            num_steps=10,
        )
        predicted_by_age.append(predicted)
        for name in total_timing:
            total_timing[name] += timing[name]
    return predicted_by_age, total_timing, len(outputs)


def sample_v1_actions(
    *,
    hook: Any,
    direct_state: Any,
    composed_state: Any,
    robot_state: Tensor,
    noise: Tensor,
    mode: Literal["A", "B"],
) -> tuple[Tensor, Tensor, dict[str, float], int]:
    """Evaluate direct/composed V1 action objectives sequentially or as one batch."""

    if mode == "B":
        batch_size = direct_state.embeddings.shape[0]
        predicted, timing = hook.sample_actions_from_state(
            stack_prefix_kv_states([direct_state, composed_state]),
            torch.cat([robot_state, robot_state], dim=0),
            torch.cat([noise, noise], dim=0),
            num_steps=10,
        )
        direct_actions, composed_actions = predicted.split((batch_size, batch_size), dim=0)
        return direct_actions, composed_actions, timing, 1
    if mode != "A":
        raise ValueError("action execution mode must be A or B")
    total_timing = {"cache_rebuild_ms": 0.0, "action_expert_ms": 0.0}
    outputs = []
    for state in (direct_state, composed_state):
        predicted, timing = hook.sample_actions_from_state(
            state,
            robot_state,
            noise,
            num_steps=10,
        )
        outputs.append(predicted)
        for name in total_timing:
            total_timing[name] += timing[name]
    return outputs[0], outputs[1], total_timing, 2


class LatentLoopTrainer:
    def __init__(
        self,
        *,
        base_model: Any,
        adapter: torch.nn.Module,
        cache_root: str | Path | None = None,
        example_source: LatentLoopExampleSource | None = None,
        output_dir: str | Path,
        config: TrainerConfig,
        weights: LossWeights,
        device: str | torch.device,
        wandb_run: Any | None = None,
    ) -> None:
        self.base_model = base_model
        self.adapter = adapter
        if (cache_root is None) == (example_source is None):
            raise ValueError("provide exactly one of cache_root or example_source")
        self.cache_root = Path(cache_root).resolve() if cache_root is not None else None
        self.example_source = example_source
        self.output = Path(output_dir).resolve()
        if self.output.exists():
            raise FileExistsError(f"refusing to overwrite or reuse training root: {self.output}")
        self.output.mkdir(parents=True, exist_ok=True)
        self.config = config
        if config.action_execution_mode not in {"A", "B"}:
            raise ValueError("action_execution_mode must be A or B")
        if config.variant == "latent_bridge" and config.action_execution_mode != "A":
            raise ValueError("batched action execution is not defined for latent_bridge")
        self.weights = weights
        self.device = torch.device(device)
        self.wandb_run = wandb_run
        if self.cache_root is not None:
            cache_manifest = self.cache_root / "pi05_latentloop_cache_manifest.json"
            cache_payload = json.loads(cache_manifest.read_text(encoding="utf-8"))
            self.provenance = {
                "training_source_mode": "persistent_teacher_cache_v2",
                "training_source_id": _sha256(cache_manifest),
                "cache_root": str(self.cache_root),
                "cache_manifest": str(cache_manifest),
                "cache_manifest_sha256": _sha256(cache_manifest),
                "source_hashes": cache_payload["metadata"]["source_hashes"],
                "source_lock_id": cache_payload["metadata"]["source_lock_id"],
                "cache_schema_version": cache_payload["schema_version"],
                "base_checkpoint": cache_payload["metadata"]["checkpoint"],
                "action_horizon_h": cache_payload["metadata"]["action_horizon_h"],
                "execution_horizon_r": cache_payload["metadata"]["execution_horizon_r"],
                "split_contract": cache_payload["metadata"]["split_contract"],
                "split_contract_sha256": cache_payload["metadata"]["split_contract_sha256"],
                "noise_seed_base": cache_payload["metadata"]["noise_seed_base"],
            }
        else:
            assert self.example_source is not None
            self.provenance = dict(self.example_source.provenance)
        freeze_base_model(base_model)
        self.adapter.to(self.device)
        self.hook = PrefixKVHook(base_model)
        self.optimizer = torch.optim.AdamW(
            [parameter for parameter in adapter.parameters() if parameter.requires_grad],
            lr=config.learning_rate,
            weight_decay=config.weight_decay,
        )
        self.train_dataset = None
        self.validation_dataset = None
        self.train_loader = None
        self.validation_loader = None
        if self.cache_root is not None:
            self.train_dataset = LatentLoopSequenceDataset(
                self.cache_root,
                split="train",
                max_delta_q=3 if config.variant in {"v0", "v1"} else 1,
                one_step_only=config.variant == "latent_bridge",
                exact_delta_q=3 if config.variant == "v0" else None,
            )
            self.validation_dataset = LatentLoopSequenceDataset(
                self.cache_root,
                split="checkpoint_validation",
                max_delta_q=3 if config.variant in {"v0", "v1"} else 1,
                one_step_only=config.variant == "latent_bridge",
                exact_delta_q=3 if config.variant == "v0" else None,
            )
            generator = torch.Generator().manual_seed(config.seed)
            self.train_loader = DataLoader(
                self.train_dataset,
                batch_size=config.batch_size,
                shuffle=True,
                generator=generator,
                num_workers=config.num_workers,
                collate_fn=lambda examples: examples,
            )
            self.validation_loader = DataLoader(
                self.validation_dataset,
                batch_size=1,
                shuffle=False,
                num_workers=0,
                collate_fn=lambda examples: examples,
            )
        elif config.num_workers != 0:
            raise ValueError("online teacher streaming requires num_workers=0")
        (self.output / "optimizer_param_names.txt").write_text(
            "\n".join(optimizer_parameter_names(adapter)) + "\n", encoding="utf-8"
        )
        (self.output / "config.json").write_text(
            json.dumps(
                {
                    "trainer": asdict(config),
                    "loss_weights": asdict(weights),
                    **adapter_checkpoint_config(adapter),
                    "adapter_trainable_parameters": adapter.trainable_parameters,
                    "provenance": self.provenance,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        base_total = sum(parameter.numel() for parameter in base_model.parameters())
        freeze_snapshot = {
            "base_total_parameters": base_total,
            "base_trainable_parameters": sum(
                parameter.numel() for parameter in base_model.parameters() if parameter.requires_grad
            ),
            "adapter_total_parameters": sum(parameter.numel() for parameter in adapter.parameters()),
            "adapter_trainable_parameters": adapter.trainable_parameters,
            "resident_total_parameters": base_total + sum(
                parameter.numel() for parameter in adapter.parameters()
            ),
            "optimizer_parameter_names": optimizer_parameter_names(adapter),
        }
        (self.output / "freeze_status_snapshot.json").write_text(
            json.dumps(freeze_snapshot, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )

    def _forward_example(self, example: dict[str, Any]) -> tuple[Tensor, dict[str, float]]:
        if self.config.variant == "v0":
            return self._forward_v0_recursive(example)
        records = example["records"]
        anchor = prefix_state_from_record(records[0], self.device)
        target = prefix_state_from_record(records[-1], self.device)
        current_prefix = prefix_embedding_from_record(records[-1], self.device)
        robot_state = torch.as_tensor(
            records[-1]["robot_state_normalized"], device=self.device, dtype=torch.float32
        ).view(1, -1)
        teacher_action = torch.as_tensor(
            records[-1]["teacher_action_chunk_normalized"], device=self.device, dtype=torch.float32
        ).view(1, self.config.action_horizon, -1)
        noise = torch.as_tensor(records[-1]["action_noise"], device=self.device, dtype=torch.float32).view(
            1, self.config.action_horizon, -1
        )
        executed = torch.cat(
            [
                torch.as_tensor(
                    record["executed_actions_postprocessed"], device=self.device, dtype=torch.float32
                ).view(
                    1, self.config.execution_horizon, -1
                )
                for record in records[:-1]
            ],
            dim=1,
        )
        delta_q = int(example["delta_q"])
        direct = self.adapter(
            anchor,
            current_prefix,
            anchor.embeddings,
            executed,
            robot_state,
            delta_q=delta_q,
            delta_a=delta_q * self.config.execution_horizon,
            full_refresh_age=delta_q,
            executed_action_lengths=torch.full(
                (executed.shape[0],),
                executed.shape[1],
                device=self.device,
                dtype=torch.long,
            ),
            intermediate_prefix_embeddings=torch.stack(
                [prefix_embedding_from_record(record, self.device).embeddings for record in records[1:]],
                dim=1,
            ),
            robot_state_history=torch.stack(
                [
                    torch.as_tensor(
                        record["robot_state_normalized"], device=self.device, dtype=torch.float32
                    ).view(1, -1)
                    for record in records[1:]
                ],
                dim=1,
            ),
        )
        composed_state = None
        composed_encoded = None
        if self.config.variant == "v1":
            composed_state = anchor
            previous_embeddings = anchor.embeddings
            for offset, record in enumerate(records[1:], start=1):
                prefix = prefix_embedding_from_record(record, self.device)
                step_robot = torch.as_tensor(
                    record["robot_state_normalized"], device=self.device, dtype=torch.float32
                ).view(1, -1)
                step_actions = torch.as_tensor(
                    records[offset - 1]["executed_actions_postprocessed"],
                    device=self.device,
                    dtype=torch.float32,
                ).view(1, self.config.execution_horizon, -1)
                composed = self.adapter(
                    composed_state,
                    prefix,
                    previous_embeddings,
                    step_actions,
                    step_robot,
                    delta_q=1,
                    delta_a=self.config.execution_horizon,
                    full_refresh_age=offset,
                    executed_action_lengths=torch.full(
                        (step_actions.shape[0],),
                        step_actions.shape[1],
                        device=self.device,
                        dtype=torch.long,
                    ),
                )
                composed_state = composed.state
                composed_encoded = composed.encoded_state
                previous_embeddings = prefix.embeddings
            assert composed_encoded is not None
            direct_actions, composed_actions, action_timing, action_expert_calls = sample_v1_actions(
                hook=self.hook,
                direct_state=direct.state,
                composed_state=composed_state,
                robot_state=robot_state,
                noise=noise,
                mode=self.config.action_execution_mode,
            )
        else:
            direct_actions, action_timing = self.hook.sample_actions_from_state(
                direct.state, robot_state, noise, num_steps=10
            )
            composed_actions = None
            action_expert_calls = 1

        direct_state_loss = normalized_kv_loss(self.adapter.codec, direct.state, target)
        direct_action_loss = action_losses(direct_actions, teacher_action, self.config.execution_horizon)
        total = weighted_v0_loss(direct_state_loss, direct_action_loss, self.weights)
        metrics = {
            "direct_state": float(direct_state_loss.detach().item()),
            **{f"direct_{name}": float(value.detach().item()) for name, value in direct_action_loss.items()},
            "action_expert_calls": float(action_expert_calls),
            "cache_rebuild_calls": float(action_expert_calls),
            "cache_rebuild_ms": float(action_timing["cache_rebuild_ms"]),
            "action_expert_ms": float(action_timing["action_expert_ms"]),
        }

        if self.config.variant == "v1":
            assert (
                composed_state is not None
                and composed_encoded is not None
                and composed_actions is not None
            )
            composed_state_loss = normalized_kv_loss(self.adapter.codec, composed_state, target)
            composed_action_loss = action_losses(composed_actions, teacher_action, self.config.execution_horizon)
            consistency = composition_loss(direct.encoded_state, composed_encoded)
            total = total + weighted_v0_loss(composed_state_loss, composed_action_loss, self.weights)
            total = total + self.weights.composition * consistency
            metrics.update(
                {
                    "composed_state": float(composed_state_loss.detach().item()),
                    "composition": float(consistency.detach().item()),
                    **{
                        f"composed_{name}": float(value.detach().item())
                        for name, value in composed_action_loss.items()
                    },
                }
            )
            metrics["primary_executed"] = float(composed_action_loss["executed"].detach().item())
        else:
            metrics["primary_executed"] = float(direct_action_loss["executed"].detach().item())
        metrics["loss"] = float(total.detach().item())
        return total, metrics

    def _forward_v0_recursive(self, example: dict[str, Any]) -> tuple[Tensor, dict[str, float]]:
        records = example["records"]
        if int(example["delta_q"]) != 3 or len(records) != 4:
            raise ValueError("V0 primary training examples must be anchor plus ages 1,2,3")
        anchor = prefix_state_from_record(records[0], self.device)
        steps: list[V0AgeInput] = []
        for offset, record in enumerate(records[1:], start=1):
            executed = torch.as_tensor(
                records[offset - 1]["executed_actions_postprocessed"],
                device=self.device,
                dtype=torch.float32,
            ).view(1, self.config.execution_horizon, -1)
            steps.append(
                V0AgeInput(
                    current_prefix=prefix_embedding_from_record(record, self.device),
                    executed_actions=executed,
                    robot_state=torch.as_tensor(
                        record["robot_state_normalized"], device=self.device, dtype=torch.float32
                    ).view(1, -1),
                    target_state=prefix_state_from_record(record, self.device),
                    action_noise=torch.as_tensor(
                        record["action_noise"], device=self.device, dtype=torch.float32
                    ).view(1, self.config.action_horizon, -1),
                    teacher_action_chunk=torch.as_tensor(
                        record["teacher_action_chunk_normalized"], device=self.device, dtype=torch.float32
                    ).view(1, self.config.action_horizon, -1),
                )
            )
        outputs = recursive_v0_unroll(
            self.adapter,
            anchor,
            steps,
            execution_horizon=self.config.execution_horizon,
        )
        losses: list[Tensor] = []
        metrics: dict[str, float] = {}
        executed_metrics: list[Tensor] = []
        predicted_by_age, action_timing, action_expert_calls = sample_v0_actions_by_age(
            hook=self.hook,
            outputs=outputs,
            steps=steps,
            mode=self.config.action_execution_mode,
        )
        for output, step, predicted_actions in zip(outputs, steps, predicted_by_age, strict=True):
            state_loss = normalized_kv_loss(
                self.adapter.codec,
                output.transition.state,
                output.target_state,
            )
            actions = action_losses(
                predicted_actions,
                output.teacher_action_chunk,
                self.config.execution_horizon,
            )
            losses.append(weighted_v0_loss(state_loss, actions, self.weights))
            executed_metrics.append(actions["executed"])
            metrics[f"age{output.age}_state"] = float(state_loss.detach().item())
            for name, value in actions.items():
                metrics[f"age{output.age}_{name}"] = float(value.detach().item())
            metrics[f"age{output.age}_consumed_predicted_previous"] = float(
                output.consumed_predicted_previous
            )
        metrics["action_expert_calls"] = float(action_expert_calls)
        metrics["cache_rebuild_calls"] = float(action_expert_calls)
        metrics["cache_rebuild_ms"] = float(action_timing["cache_rebuild_ms"])
        metrics["action_expert_ms"] = float(action_timing["action_expert_ms"])
        total = torch.stack(losses).mean()
        first_r = torch.stack(executed_metrics).mean()
        metrics["direct_executed"] = float(first_r.detach().item())
        metrics["recursive_first_r"] = float(first_r.detach().item())
        metrics["primary_executed"] = float(first_r.detach().item())
        metrics["loss"] = float(total.detach().item())
        return total, metrics

    @torch.no_grad()
    def validate(self, max_examples: int | None = None) -> dict[str, float]:
        self.adapter.eval()
        totals: dict[str, float] = {}
        count = 0
        limit = max_examples if max_examples is not None else self.config.validation_examples
        if self.example_source is not None:
            if limit is None or limit < 1:
                raise ValueError("streaming validation requires a positive fixed example limit")
            validation_examples = self.example_source.iter_validation_examples(limit)
        else:
            assert self.validation_loader is not None
            validation_examples = (examples[0] for examples in self.validation_loader)
        for example in validation_examples:
            _, metrics = self._forward_example(example)
            for name, value in metrics.items():
                totals[name] = totals.get(name, 0.0) + value
            count += 1
            if limit is not None and count >= limit:
                break
        self.adapter.train()
        if count == 0:
            raise RuntimeError("validation source produced no examples")
        return {name: value / max(count, 1) for name, value in totals.items()}

    def raw_loss_calibration(self, examples: int = 32) -> dict[str, Any]:
        started = time.time()
        metrics = self.validate(max_examples=examples)
        if self.config.variant == "v0":
            completion_marker = "V0_RAW_LOSS_CALIBRATION_COMPLETE"
        elif self.config.variant == "v1" and self.example_source is not None:
            completion_marker = "V1_STREAMING_RAW_LOSS_CALIBRATION_COMPLETE"
        else:
            completion_marker = "V1_RAW_LOSS_CALIBRATION_COMPLETE"
        payload = {
            "schema_version": 2,
            "complete": True,
            completion_marker: True,
            "markers": [completion_marker],
            "variant": self.config.variant,
            "action_execution_mode": self.config.action_execution_mode,
            "examples": examples,
            "adapter_state": "deterministically initialized, untrained",
            "adapter_trainable_parameters": self.adapter.trainable_parameters,
            "source_lock_id": self.provenance["source_lock_id"],
            "training_source_mode": self.provenance["training_source_mode"],
            "training_source_id": self.provenance["training_source_id"],
            "raw_metrics": metrics,
            "elapsed_seconds": time.time() - started,
            "peak_vram_bytes": (
                torch.cuda.max_memory_allocated(self.device) if self.device.type == "cuda" else 0
            ),
        }
        if "cache_manifest_sha256" in self.provenance:
            payload["cache_manifest_sha256"] = self.provenance["cache_manifest_sha256"]
        if self.example_source is not None:
            payload["streaming_source_statistics"] = self.example_source.statistics()
        payload["raw_loss_calibration_id"] = hashlib.sha256(
            json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        (self.output / "raw_loss_calibration.json").write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        return payload

    def train(self) -> dict[str, Any]:
        from tqdm.auto import tqdm

        torch.manual_seed(self.config.seed)
        self.adapter.train()
        iterator = self._new_train_iterator()
        best_executed = float("inf")
        best_step = 0
        started = time.time()
        progress = tqdm(range(1, self.config.max_steps + 1), desc=f"pi0.5 LatentLoop {self.config.variant}")
        for step in progress:
            try:
                examples = next(iterator)
            except StopIteration:
                iterator = self._new_train_iterator()
                examples = next(iterator)
            self.optimizer.zero_grad(set_to_none=True)
            losses = []
            batch_metrics: list[dict[str, float]] = []
            for example in examples:
                loss, metrics = self._forward_example(example)
                losses.append(loss)
                batch_metrics.append(metrics)
            batch_loss = torch.stack(losses).mean()
            batch_loss.backward()
            torch.nn.utils.clip_grad_norm_(self.adapter.parameters(), self.config.max_grad_norm)
            self.optimizer.step()

            averaged = {
                name: sum(item[name] for item in batch_metrics) / len(batch_metrics)
                for name in batch_metrics[0]
            }
            if step == 1:
                gradient_payload = {
                    "step": 1,
                    "finite_loss": bool(torch.isfinite(batch_loss).item()),
                    "base_gradients_present": any(
                        parameter.grad is not None for parameter in self.base_model.parameters()
                    ),
                    "adapter_parameters_with_gradient": sum(
                        int(parameter.grad is not None) for parameter in self.adapter.parameters()
                    ),
                    "adapter_parameters": sum(1 for _ in self.adapter.parameters()),
                }
                (self.output / "gradient_sanity.json").write_text(
                    json.dumps(gradient_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
                )
            if step % self.config.log_interval == 0 or step == 1:
                log_record = {"step": step, **averaged, "elapsed_seconds": time.time() - started}
                with (self.output / "train_metrics.jsonl").open("a", encoding="utf-8") as handle:
                    handle.write(json.dumps(log_record, sort_keys=True) + "\n")
                progress.set_postfix(
                    loss=f"{averaged['loss']:.4g}",
                    first_r=f"{averaged['primary_executed']:.4g}",
                )
            if self.wandb_run is not None and (
                step % self.config.wandb_log_interval == 0 or step == 1
            ):
                self.wandb_run.log({f"train/{key}": value for key, value in averaged.items()}, step=step)

            if step % self.config.validation_interval == 0 or step == self.config.max_steps:
                validation = self.validate()
                primary = validation["primary_executed"]
                record = {"step": step, "validation": validation, "elapsed_seconds": time.time() - started}
                with (self.output / "validation.jsonl").open("a", encoding="utf-8") as handle:
                    handle.write(json.dumps(record, sort_keys=True) + "\n")
                if self.wandb_run is not None:
                    self.wandb_run.log(
                        {f"validation/{key}": value for key, value in validation.items()}, step=step
                    )
                if primary < best_executed:
                    best_executed = primary
                    best_step = step
                    self._save(step, "best.pt", validation)
            if step % self.config.save_interval == 0 or step == self.config.max_steps:
                self._save(step, f"step_{step:06d}.pt", None)
        if self.config.variant == "v0":
            completion_marker = "V0_TRAIN_COMPLETE"
        elif self.config.variant == "v1" and self.example_source is not None:
            completion_marker = "V1_STREAMING_SCREEN_TRAIN_COMPLETE"
        elif self.config.variant == "v1":
            completion_marker = "V1_TRAIN_COMPLETE"
        else:
            completion_marker = "LATENT_BRIDGE_TRAIN_COMPLETE"
        checkpoint_selection_metric = {
            "v0": "mean_recursive_age1_age2_age3_executed_action_mse",
            "v1": "composed_sequential_executed_action_mse",
            "latent_bridge": "direct_executed_action_mse",
        }[self.config.variant]
        summary = {
            "complete": True,
            "variant": self.config.variant,
            "steps": self.config.max_steps,
            "best_step": best_step,
            "best_validation_first_r_action_mse": best_executed,
            "checkpoint_selection_metric": checkpoint_selection_metric,
            "optimizer": "AdamW",
            "learning_rate": self.config.learning_rate,
            "learning_rate_schedule": "constant",
            "weight_decay": self.config.weight_decay,
            "adapter_trainable_parameters": self.adapter.trainable_parameters,
            "action_execution_mode": self.config.action_execution_mode,
            "source_lock_id": self.provenance["source_lock_id"],
            "training_source_mode": self.provenance["training_source_mode"],
            "training_source_id": self.provenance["training_source_id"],
            completion_marker: True,
            "elapsed_seconds": time.time() - started,
            "peak_vram_bytes": (
                torch.cuda.max_memory_allocated(self.device) if self.device.type == "cuda" else 0
            ),
        }
        if self.example_source is not None:
            summary["streaming_source_statistics"] = self.example_source.statistics()
        (self.output / "run_summary.json").write_text(
            json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        return summary

    def _new_train_iterator(self) -> Iterator[list[dict[str, Any]]]:
        if self.example_source is None:
            assert self.train_loader is not None
            return iter(self.train_loader)
        source = iter(self.example_source.iter_train_examples())

        def batches() -> Iterator[list[dict[str, Any]]]:
            while True:
                yield [next(source) for _ in range(self.config.batch_size)]

        return batches()

    def _save(self, step: int, name: str, validation: dict[str, float] | None) -> None:
        checkpoints = self.output / "checkpoints"
        checkpoints.mkdir(exist_ok=True)
        target = checkpoints / name
        temporary = target.with_suffix(target.suffix + ".tmp")
        torch.save(
            {
                "adapter": self.adapter.state_dict(),
                "optimizer": self.optimizer.state_dict(),
                "step": step,
                "validation": validation,
                "config": {
                    "trainer": asdict(self.config),
                    "loss_weights": asdict(self.weights),
                    **adapter_checkpoint_config(self.adapter),
                    "provenance": self.provenance,
                },
            },
            temporary,
        )
        temporary.replace(target)
